spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dto_practice?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: dto
    password: dtopass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.study.dtopractice.bbs
  configuration:
    map-underscore-to-camel-case: true